# Generated by Django 5.0.4 on 2024-05-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_invoice', models.CharField(max_length=355)),
                ('code_order_invoice', models.CharField(max_length=355)),
                ('date', models.DateField()),
                ('cart_data', models.JSONField()),
                ('total_cases', models.IntegerField()),
                ('total_sum', models.FloatField()),
                ('past_due', models.CharField(max_length=55)),
                ('is_sent_mail', models.BooleanField(default=False)),
                ('ship_via', models.CharField(max_length=100)),
                ('terms', models.CharField(max_length=55)),
                ('customer', models.ManyToManyField(to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_data', models.JSONField()),
                ('cases_number', models.IntegerField()),
                ('total_sum', models.FloatField()),
                ('date_creating', models.DateField(auto_now=True)),
                ('delivery_date', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
                ('customer', models.ManyToManyField(to='customers.customer')),
            ],
        ),
    ]
