# Generated by Django 5.0.6 on 2024-05-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='ship_via',
            field=models.CharField(default='warehouse', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
