# Generated by Django 5.0.6 on 2024-05-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_invoices_ship_via_alter_orders_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='customer',
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_date',
            field=models.DateField(),
        ),
    ]
