# Generated by Django 5.0.6 on 2024-05-30 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_email'),
        ('orders', '0004_remove_invoices_customer_alter_orders_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='customers.customer'),
            preserve_default=False,
        ),
    ]
