# Generated by Django 5.0.4 on 2024-05-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=355)),
                ('address', models.CharField(max_length=455)),
                ('google_maps_path', models.TextField()),
                ('phone', models.CharField(max_length=155)),
                ('contact_person', models.CharField(max_length=55)),
                ('zip_code', models.CharField(max_length=255)),
                ('tax_id', models.CharField(max_length=355)),
                ('open_at_hour', models.TimeField()),
                ('licence_number', models.CharField(max_length=355)),
                ('price_type', models.CharField(max_length=55)),
                ('last_call', models.DateField(null=True)),
                ('last_visiting', models.DateField(null=True)),
                ('last_testing', models.DateField(null=True)),
                ('last_order', models.DateField(null=True)),
                ('state', models.ManyToManyField(to='products.state')),
            ],
        ),
    ]
